use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
port = System.get_env("PORT", 80)
host = System.get_env("APP_HOST")

level =
  "LOG_LEVEL"
  |> System.get_env("info")
  |> String.to_atom()

config :snowhite, SnowhiteWeb.Endpoint,
  url: [host: host, port: port],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: level
